### ISSUE TITLE
The playback time of the exported Ogg audio file will be incorrect.

### ISSUE THREAD

**Issue by BambooTuna** [pion/webrtc#1537]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you expect?
If you see the PR(#1536 ) and there is no problem, please merge.

### What happened?
When trying to record the microphone input of a user connected to webrtc using oggwriter.
An audio file with a playback time longer than the recorded time has been created. It doesn't actually play that time, and the header seems to be broken.

The default value for previousTimestamp is 1 instead of 0. The playback time of the ogg file created by it is supposed to be strange.
As a result, the value of previousGranulePosition starts with a large number, and the playback time becomes several hours or more.

I've created a modified PR so I'd be happy if you could review it for correctness.

**Comment by Sean-Der** [comment]
Resolved by 1ffa87eb0733e7bfc6a50dcd2b2bac7d93c380ad

Thank you so much @BambooTuna

**Comment by sampleref** [comment]
Hi

I am still seeing same issue, the ogg file created with opus code by using  oggwriter shows duration very large

 When recorded a small ogg file of ~30 secs, it shows file duration as ~ 223 Hours, any headers or page info should I verify ?

I am using Pion WebRTC v3.0.17, and I can see this above changes are available
